name: Two

on:
  workflow_call:
    inputs:
      EmailOnFailure:
        description: "True if an email should be sent when the workflow fails."
        required: true
        type: boolean

jobs:
  email_test:
    runs-on: windows-latest
    steps:
      - run: |
          exit 0
      - name: Notify on Failure
        if: ${{ failure() && inputs.EmailOnFailure }}
        run: |
          Write-Host "World"
        # uses: dawidd6/action-send-mail@v3
        # with:
        #   server_address: smtp.gmail.com
        #   server_port: 465
        #   username: ${{ secrets.NotifierUsername }}
        #   password: ${{ secrets.NotifierPassword }}
        #   subject: Nightly functional test failure
        #   body: The Def_Tenant1 test failed.  Please look at the "Nightly Product Functional Tests" workflow for more details.
        #   to: ${{ steps.extract-email.outputs.emails }}
        #   from: ScubaGear Notifier
